version: '3'

services:
  # Postgress database
  pgdb:
    image: postgres:17
    container_name: database
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASEPASSWORD}
      POSTGRES_USER: ${DATABASEUSER}
      POSTGRES_DB: ${DATABASENAME}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  broker:
    image: apache/kafka:4.0.0
    container_name: broker
    ports:
      - "9092:9092"


volumes:
  pgdata:
